steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
  id: login
   
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMG_DEST}:${SHORT_SHA}'
    - '-f'
    - 'Dockerfile'
    - '.'
  id: build

- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - |
    docker push ${_IMG_DEST}:${SHORT_SHA} &&
    docker image inspect ${_IMG_DEST}:${SHORT_SHA} --format '{{index .RepoDigests 0}}' > image-digest.txt &&
    cat image-digest.txt
  id: push

- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
  - -c
  - |
     itoken=$(curl -X POST -H "content-type: application/json" \
     -H "Authorization: Bearer $(gcloud auth print-access-token)" \
     -d '{"audience": "${_SERVICE_URL}"}' \
     https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${_SERVICE_ACCOUNT}:generateIdToken) && \
     curl -X POST \
     -H "Authorization: Bearer $(echo $itoken | awk -F'\"' '{print $4}')" \
     -H "Content-Type: application/json" \
     -d "{\"image_url\": \"$(cat image-digest.txt)\"}" \
     ${_SERVICE_URL}/all
  waitFor: ["push"]
  id: vulnsign

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - '${_IMG_DEST}:${SHORT_SHA}'
    - '${_IMG_DEST}:latest'
  waitFor: ["vulnsign"]

substitutions:
    _IMG_DEST: gregnrobinson/cloud-tools
    
availableSecrets:
  secretManager:
   - versionName: projects/${_PROJECT_ID}/secrets/${_DOCKER_PASSWORD_SECRET}/versions/${_DOCKER_PASSWORD_SECRET_VERSION}
     env: 'PASSWORD'
   - versionName: projects/${_PROJECT_ID}/secrets/${_DOCKER_ID_SECRET}/versions/${_DOCKER_ID_SECRET_VERSION}
     env: 'USERNAME'
     
timeout: 1200s
