steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
  id: login
   
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMG_DEST}:${_TAG}'
    - '-f'
    - 'Dockerfile'
    - '.'
  id: build

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_IMG_DEST}:${_TAG}'
  id: push

substitutions:
    _IMG_DEST: gregnrobinson/cloud-tools
    
availableSecrets:
  secretManager:
   - versionName: projects/${_PROJECT_ID}/secrets/${_DOCKER_PASSWORD_SECRET}/versions/${_DOCKER_PASSWORD_SECRET_VERSION}
     env: 'PASSWORD'
   - versionName: projects/${_PROJECT_ID}/secrets/${_DOCKER_ID_SECRET}/versions/${_DOCKER_ID_SECRET_VERSION}
     env: 'USERNAME'
     
timeout: 1200s
