version: "3.8"
services:
  dev:
    hostname: cloud-tools
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    image: gregnrobinson/cloud-tools
    volumes:
      - "./config/profile/bashrc:/root/.bashrc"
      - "./config/kubeconfigs:/root/.kube/"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    entrypoint: /bin/bash
    command: -c "./bootstrap.sh"