version: "3.8"
services:
  cloud-tools:
    args:
      SHORT_SHA: ${SHORT_SHA}
    hostname: cloud-tools
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    image: gregnrobinson/cloud-tools
    volumes:
      - "./config/profile/bashrc:/root/.bashrc"
      - "./config/kubeconfigs:/root/.kube/"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      SHORT_SHA: ${SHORT_SHA}
      GIT_EMAIL: "gregnrobinson@gmail.com"
      GIT_USER: "gregnrobinson"
      WG_SUDO: "1"
    entrypoint: /bin/bash
    command: -c "./bootstrap.sh"