version: "3.8"
services:
  dev:
    hostname: vscode_dev
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - "./wg0.conf:/etc/wireguard/wg0.conf"
      - "./config/ssh/:/root/.ssh/"
      - "./config/profile/bashrc:/root/.bashrc"
      - "./config/kubeconfigs:/root/.kube/"
      - "./config/packages:/root/packages/"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      KUBECONFIG: 
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    entrypoint: /bin/bash
    command: -c "./bootstrap.sh"