version: '3'
services:
  cloud-tools:
    # Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    # https://hub.docker.com/layers/186906826/gregnrobinson/cloud-tools/v1.1.26/images/sha256-3e62efbae1e2a6ab66f33beb3b9059967319fced6e23fc0dc6cdb23bc27a2967?context=repo
    image: gregnrobinson/cloud-tools@sha256:3e62efbae1e2a6ab66f33beb3b9059967319fced6e23fc0dc6cdb23bc27a2967 # AMD64 Digest
    volumes:
      - ..:/workspace:cached
      - ./config:/root:cached
    entrypoint: /bin/bash
    command: -c "sleep infinity"
