name: ci-cloud-tools

env:
  NAME: cloud-tools
  IMAGE: gregnrobinson/cloud-tools
  TAG: v1.1.0
  WORKDIR: .

on:
  push:
    branches:
    - main
    - feature/docker-compose-build
  release:
    types:
    - created
  workflow_dispatch:

jobs:
  timeout-minutes: 30
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build
      working-directory: ${{ env.WORKDIR }}
      run: >
        docker buildx build
        --platform=linux/amd64,linux/arm64
        -t ${{ env.IMAGE }}:${{ env.GITHUB_SHA_SHORT }}
        --output=type=image,push=true
        ${GITHUB_WORKSPACE}/${{ env.WORKDIR }}
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE }}:${{ env.GITHUB_SHA_SHORT }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: os,library
        severity: CRITICAL
    - name: Push / Tag Latest
      working-directory: ${{ env.WORKDIR }}
      run: >
        AMD64=$(docker manifest inspect ${{ env.IMAGE }}:${{ env.TAG }} | jq '.manifests[0].digest')
        ARM64=$(docker manifest inspect ${{ env.IMAGE }}:${{ env.TAG }} | jq '.manifests[1].digest')
        
        docker manifest push docker.io/gregnrobinson/cloud-tools:${{ env.TAG }}@${ARM64}
        docker manifest push docker.io/gregnrobinson/cloud-tools:${{ env.TAG }}@${AMD64}