name: Build

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
  workflow_dispatch:

jobs:
  docker-compose-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build / Push Sha
      id: build_sha
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: gregnrobinson/cloud-tools:${{ env.GITHUB_SHA_SHORT }}
