name: ci-cloud-tools

env:
  NAME: cloud-tools
  IMAGE: gregnrobinson/cloud-tools
  TAG: v1.1.0
  WORKDIR: .

on:
  push:
    branches:
    - main
    - feature/docker-compose-build
  release:
    types:
    - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build
      working-directory: ${{ env.WORKDIR }}
      run: >
        docker buildx build
        --platform=linux/amd64,linux/arm64
        -t ${{ env.IMAGE }}:${{ env.GITHUB_SHA_SHORT }}
        --output=type=docker
        ${GITHUB_WORKSPACE}/${{ env.WORKDIR }}
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE }}:${{ env.GITHUB_SHA_SHORT }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: os,library
        severity: CRITICAL,HIGH
    - name: Tag Latest
      working-directory: ${{ env.WORKDIR }}
      run: |
        docker image tag ${{ env.IMAGE }}:${{ env.GITHUB_SHA_SHORT }} ${{ env.IMAGE }}:${{ env.TAG }} &&\
        docker image push ${{ env.IMAGE }}:${{ env.TAG }}